---
title: "Combined Data"
output: html_document
date: "2024-07-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
# install.packages("devtools")
#devtools::install_github("bio-oracle/biooracler")
library(biooracler)
library(tidyverse)
library(stars)
library(sf)
library(abind)
library(patchwork)
library(sp)
library(dplyr)

```

Establishing parameters (coordinates of the Gulf of Mexico)
```{r}
latitude = c(31.14, 14.37)
longitude = c(-80.63, -98.86)

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

```

2020 
```{r}
#establishing the time of 2020
time = c('2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z')
```

2020 - ssp2 (45)
```{r}
#identifying data set for surface temperature
dataset_id = "thetao_ssp245_2020_2100_depthsurf"

variables = "thetao_mean"

temp_ssp2_2020 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)



#identifying data set for bathymetry 
dataset_id = "mlotst_ssp245_2020_2100_depthsurf"

variables = "mlotst_mean"

#downloading layer to the according varibale 
mld_ssp2_2020 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)



#identifying data set for chlorophyll-a consentration ssp2
dataset_id = "chl_ssp245_2020_2100_depthsurf"

variables = "chl_mean"

# downloading layer 
chl_ssp2_2020 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)
```

2020 - ssp4 (60)
```{r}
#identifying data set for surface temperature ssp4
dataset_id = "thetao_ssp460_2020_2100_depthsurf"

variables = "thetao_mean"

temp_ssp4_2020 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)



#identifying data set for bathymetry ssp4
dataset_id = "mlotst_ssp460_2020_2100_depthsurf"

variables = "mlotst_mean"

#downloading layer to the according varibale 
mld_ssp4_2020 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)



#identifying data set for chlorophyll-a consentration ssp4
dataset_id = "chl_ssp460_2020_2100_depthsurf"

variables = "chl_mean"

# downloading layer 
chl_ssp4_2020 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)
```

------------
2050 
```{r}
#reestablishing the time as 2050
time = c('2050-01-01T00:00:00Z', '2050-01-01T00:00:00Z')
```

2050 - ssp2 (45)
```{r}
#identifying data set for surface temperature
dataset_id = "thetao_ssp245_2020_2100_depthsurf"

variables = "thetao_mean"

temp_ssp2_2050 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)



#identifying data set for bathymetry 
dataset_id = "mlotst_ssp245_2020_2100_depthsurf"

variables = "mlotst_mean"

#downloading layer to the according varibale 
mld_ssp2_2050 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)



#identifying data set for chlorophyll-a consentration ssp2
dataset_id = "chl_ssp245_2020_2100_depthsurf"

variables = "chl_mean"

# downloading layer 
chl_ssp2_2050 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)
```

2050 - ssp4 (60)
```{r}
#identifying data set for surface temperature ssp4
dataset_id = "thetao_ssp460_2020_2100_depthsurf"

variables = "thetao_mean"

temp_ssp4_2050 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)



#identifying data set for bathymetry ssp4
dataset_id = "mlotst_ssp460_2020_2100_depthsurf"

variables = "mlotst_mean"

#downloading layer to the according varibale 
mld_ssp4_2050 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)



#identifying data set for chlorophyll-a consentration ssp4
dataset_id = "chl_ssp460_2020_2100_depthsurf"

variables = "chl_mean"

# downloading layer 
chl_ssp4_2050 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)
```


------------
2090 
```{r}
#reestablishing the time as 2090
time = c('2090-01-01T00:00:00Z', '2090-01-01T00:00:00Z')
```

2090 - ssp2 (45)
```{r}
#identifying data set for surface temperature
dataset_id = "thetao_ssp245_2020_2100_depthsurf"

variables = "thetao_mean"

temp_ssp2_2090 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)



#identifying data set for bathymetry 
dataset_id = "mlotst_ssp245_2020_2100_depthsurf"

variables = "mlotst_mean"

#downloading layer to the according varibale 
mld_ssp2_2090 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)



#identifying data set for chlorophyll-a consentration ssp2
dataset_id = "chl_ssp245_2020_2100_depthsurf"

variables = "chl_mean"

# downloading layer 
chl_ssp2_2090 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)
```

2090 - ssp4 (60)
```{r}
#identifying data set for surface temperature ssp4
dataset_id = "thetao_ssp460_2020_2100_depthsurf"

variables = "thetao_mean"

temp_ssp4_2090 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)



#identifying data set for bathymetry ssp4
dataset_id = "mlotst_ssp460_2020_2100_depthsurf"

variables = "mlotst_mean"

#downloading layer to the according varibale 
mld_ssp4_2090 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)



#identifying data set for chlorophyll-a consentration ssp4
dataset_id = "chl_ssp460_2020_2100_depthsurf"

variables = "chl_mean"

# downloading layer 
chl_ssp4_2090 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)
```

Extracting the occurcances 
```{r}
# reading out the occurences 
occurences = read_csv(here::here("data", "Raw", "GBIF_Occurance_data2.csv"))%>% 
  select(occurrenceStatus, decimalLatitude, decimalLongitude) %>% 
  filter(!is.na(as.numeric(decimalLatitude))) %>% 
  filter(!is.na(as.numeric(decimalLongitude)))  %>% 
  filter(occurrenceStatus == "PRESENT") %>% 
  st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), crs = "EPSG:4326")

```
extracting the pseudo absences 
```{r}
#extracting 
buffer_occurence = st_buffer(occurences, 5000)

temp_crop = crop(temp_ssp2_2020, buffer_occurence)
no_points = mask(temp_ssp2_2020, buffer_occurence, inverse=TRUE)

# takes a while, but you'll want to change the number to get close to the number of occurences you have
random_points = terra::spatSample(no_points, 10000, "random", na.rm=T, as.points=TRUE) %>% 
  st_as_sf() #should be an sf dataframe

class(random_points)

random_points = random_points %>% 
  filter(thetao_mean > 0)%>% 
  mutate(occurrenceStatus = "ABSENT") %>% relocate(geometry, .after = occurrenceStatus)


random_points$thetao_mean <- NULL

All_occurance <- rbind(occurences, random_points)
```

```{r}

testSet = c(
  terra::extract(c(temp_ssp2_2020, temp_ssp4_2020, 
                   chl_ssp2_2020, chl_ssp4_2020,
                   mld_ssp2_2020, mld_ssp4_2020), All_occurance)
   ) %>%
  cbind(All_occurance) 

testSet$ID = NULL
for (x in 1:5) {
  testSet$ID.x = NULL
}

testSet = na.omit(testSet)

colnames(testSet)

names(testSet) <- c("temp_ssp2_20","temp_ssp4_20","chl_ssp2_20","chl_ssp4_20","mld_ssp2_20", "mld_ssp4_20",
                    "occurance_status", "geometry")
```

connor's forloop

```{r}
#extracting 

buffer_occurence = st_buffer(occurences, 5000)
combined_data = data.frame()

n = 18
#vector of all the rasters we are testing
rasters = c(temp_ssp2_2020_extract, temp_ssp2_2050, temp_ssp2_2090, temp_ssp4_2020, temp_ssp4_2050, temp_ssp4_2090, mld_ssp2_2020, mld_ssp2_2050, mld_ssp2_2090, mld_ssp4_2020, mld_ssp4_2050, mld_ssp4_2090, chl_ssp2_2020, chl_ssp2_2050, chl_ssp2_2090, chl_ssp4_2020, chl_ssp4_2050, chl_ssp4_2090)
#creates the necessary means for the rasters
Crops = rep(NaN, n)
extracts = rep(NaN, n)

#need to figure out how to combine the rasters so this for loop works
for (i in 1:18) {
#problem with cropping a portion of a vector
Crops[i] = terra::crop(rasters[i], buffer_occurence)
no_points = terra::mask(rasters[i], buffer_occurence, inverse=TRUE)

extracts[i] = terra::extract(rasters[i], occurences) %>% 
  cbind(occurences) %>% 
  st_as_sf() %>% 
  select(means[i], occurrenceStatus)

combined_data %>% 
  mutate(extracts[i])
}
```

```{r}
model_data = rbind(random_points, temp_ssp2_2020_extract)%>% 
  st_as_sf()

ggplot(model_data) +
  geom_sf(aes(color = occurrenceStatus)) +
  theme_bw()
```



