---
title: "attempt4"
date: "2024-07-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
#install.packages("ranger")
#install.packages("randomForest")
#install.packages("vip")

library(tidyverse)
library(tidymodels)
library(here)
library(nnet)
library(ranger)
library(glue)
library(randomForest)
library(vip)
library(parsnip)
library(stars)
library(raster)
library(terra)
library(patchwork)

set.seed(42)

```

##Reading in the data
```{r}
All_data = read_csv(here::here("Data_of_everything_updated.csv")) %>% 
  mutate(occurance_status = as.factor(occurance_status)) %>% 
  group_by(occurance_status) %>% 
  sample_n(size = 370)

data_split = initial_split(All_data, prop = 0.75, strata = occurance_status)

train = training(data_split)
test = testing(data_split)


train |> group_by(occurance_status) |> summarize(n = n())

#Create flows for the cross-validation 
cv_folds = vfold_cv(train, v=5)

#Create a model recipe 
ws_recipe = recipe(occurance_status ~ temp_current + chl_current + mld_current, data = train) %>% 
  #normalize all the numeric predictors to ensure they are all in the same scale 
  step_normalize(all_numeric_predictors())

ws_recipe
```
```{r}
#Random Forest model 
  #fin_model <- randomForest(fin_sighting,
   #mode = "classification",
   #trees = tune(),
  # min_n = tune()
  #)

ws_model <- rand_forest(
  mode = "classification",
  trees = tune(),
  min_n = tune()
) %>%
  set_engine("randomForest")

ws_model
```
```{r}
?add_model

#create work flow
ws_workflow = workflow() %>%
  add_model(ws_model) %>%
  add_recipe(ws_recipe)

ws_workflow
```



```{r}
ws_cv_tune = ws_cv_tune <- ws_workflow %>%
  tune_grid(resamples = cv_folds,
   metrics = metric_set(roc_auc, accuracy) )

save(ws_cv_tune, file= here::here("Whale_shark_tuned.rda"))

load (file=here::here("Whale_shark_tuned.rda"))
```

```{r}
collect_metrics(ws_cv_tune)
```

```{r}
autoplot(ws_cv_tune) +
  theme_bw()
```

```{r}
ws_final = finalize_workflow(ws_workflow, select_best(ws_cv_tune, metric = "roc_auc" ))

train_fit_ws = fit(ws_final, train)

train_fit_ws
```

```{r}
#Get the prediction prob for the test data, get the class prediction
test_predict_whaleshark = predict(train_fit_ws, test) %>%
  bind_cols(test) %>%
  mutate(occurance_status = as.factor(occurance_status))

#Give the predicted prob of being in each class
test_predict2_whaleshark = predict(train_fit_ws, test, type = "prob") %>% #gets the testing prediction
  bind_cols(test) %>%
  mutate(occurance_status = as.factor(occurance_status)) %>% 
  mutate(check = .pred_ABSENT + .pred_PRESENT) %>% 
  mutate(pred_binary = ifelse(.pred_PRESENT >= 0.75, "1", "0"))
```

```{r}
#Measure the accuracy
accuracy (test_predict_whaleshark, truth = occurance_status, estimate=.pred_class)
```
```{r}
test_roc_acu_present = roc_curve(test_predict2_whaleshark, occurance_status, .pred_PRESENT)

test_roc_acu_absent = roc_curve(test_predict2_whaleshark, occurance_status, .pred_ABSENT)
```

```{r}
test_predict_whaleshark %>%
  conf_mat(truth= occurance_status, estimate = .pred_class) %>%
  autoplot(type = "heatmap") +
  theme_bw()+
  theme(axis.text.x = element_text(angle=30, hjust = 1)) +
  labs(title="Random Forest")

ggplot(test_predict_whaleshark, aes(long, lat, color = occurance_status)) +
  geom_point()
```


```{r}
autoplot(test_roc_acu_absent) +
  theme_bw()
```

```{r}
shapefile <- st_read("shape_file")

names(shapefile) = c( "Temp", "Temp_245_2090", "Temp_460_2090", "Chlor", "Chlor_245_2090", "Chlor_460_2090",
  "Mlost", "Mlost_245_2090", "Mlost_460_2090", "Temp_245_2050", "Temp_460_2050", "Chlor_245_2050", "Chlor_460_2050",
  "Mlost_245_2050", "Mlost_460_2050", "geometry")
```

splitting up the data to make our lives easier
```{r}
ssp2_2050 <- dplyr::select(shapefile, c("Temp_245_2050", "Chlor_245_2050", "Mlost_245_2050", "geometry" )) 
names(ssp2_2050) = c("temp_current", "chl_current", "mld_current", "geometry")

ssp4_2050 <- dplyr::select(shapefile, c("Temp_460_2050", "Chlor_460_2050", "Mlost_460_2050", "geometry" )) 
names(ssp4_2050) = c("temp_current", "chl_current", "mld_current", "geometry")

ssp2_2090 <- dplyr::select(shapefile, c("Temp_245_2090", "Chlor_245_2090", "Mlost_245_2050", "geometry" )) 
names(ssp2_2090) = c("temp_current", "chl_current", "mld_current", "geometry")

ssp4_2090 <- dplyr::select(shapefile, c("Temp_460_2090", "Chlor_460_2090", "Mlost_460_2090", "geometry" )) 
names(ssp4_2090) = c("temp_current", "chl_current", "mld_current", "geometry")
```

predicting probability for other stuff 
```{r}
predict_ssp2_2050 = predict(train_fit_ws, ssp2_2050, type = "prob") %>% #gets the testing prediction
  bind_cols(ssp2_2050) %>%
  mutate(check = .pred_ABSENT + .pred_PRESENT) %>% 
  mutate(pred_binary = ifelse(.pred_PRESENT >= 0.75, "1", "0"))

predict_ssp4_2050 = predict(train_fit_ws, ssp4_2050, type = "prob") %>% #gets the testing prediction
  bind_cols(ssp4_2050) %>%
  mutate(check = .pred_ABSENT + .pred_PRESENT) %>% 
  mutate(pred_binary = ifelse(.pred_PRESENT >= 0.75, "1", "0"))

predict_ssp2_2090 = predict(train_fit_ws, ssp2_2090, type = "prob") %>% #gets the testing prediction
  bind_cols(ssp2_2090) %>%
  mutate(check = .pred_ABSENT + .pred_PRESENT) %>% 
  mutate(pred_binary = ifelse(.pred_PRESENT >= 0.75, "1", "0"))

predict_ssp4_2090 = predict(train_fit_ws, ssp4_2090, type = "prob") %>% #gets the testing prediction
  bind_cols(ssp4_2090) %>%
  mutate(check = .pred_ABSENT + .pred_PRESENT) %>% 
  mutate(pred_binary = ifelse(.pred_PRESENT >= 0.75, "1", "0"))
```


```{r}
random_points_sf <- st_as_sf(test_predict2_whaleshark, coords = c("long", "lat"))

random_rast <- random_points_sf %>%
  select(.pred_PRESENT) %>%
  st_rasterize() %>%
  aggregate(FUN = mean, by = random_points_sf) %>%
  as.data.frame(xy = TRUE) %>%
  st_as_sf()
```

SDM woooo
```{r}
predict_ssp2_2050 = st_as_sf(predict_ssp2_2050)

plot(predict_ssp2_2050[, 2])

ggplot()+
  geom_raster(data = predict_ssp2_2050)
```

<<<<<<< HEAD:Naomi's updated code we love her.Rmd
sbm plot i hope
```{r}
ggplot() +
  geom_sf(data = test_predict2_whaleshark, aes(oc)) +
  theme_bw() +
  scale_color_viridis_c() +
  labs(x = "Longitude", y = "Latitude", fill = "pH")
```
=======
>>>>>>> 8d1ca39ffa1362b0b4a302acbeecc8b05609c131:SDM_actual.Rmd

